services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: instruction_presenter
      POSTGRES_USER: instruction_presenter
      POSTGRES_PASSWORD: instruction_presenter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
