"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _hosts_from_env(var_name: str) -> list[str]:
    """Comma-separated hostnames; whitespace trimmed; empty entries dropped."""
    raw = os.environ.get(var_name, '')
    if not raw:
        return []
    return [h.strip() for h in raw.split(',') if h.strip()]


def _allowed_hosts_from_environment() -> list[str]:
    """
    ALLOWED_HOSTS env: comma-separated list (e.g. app.azurewebsites.net,custom.domain).
    On Azure App Service, WEBSITE_HOSTNAME is appended if not already listed.
    """
    hosts: list[str] = []
    seen: set[str] = set()
    for h in _hosts_from_env('ALLOWED_HOSTS'):
        key = h.lower()
        if key not in seen:
            seen.add(key)
            hosts.append(h)
    website = os.environ.get('WEBSITE_HOSTNAME', '').strip()
    if website and website.lower() not in seen:
        hosts.append(website)
    return hosts


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7*4^8zs@bf%!lwjgeb=_2^(lp9t&^td$*0um9^b4p&16^n7z8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_env_allowed = _allowed_hosts_from_environment()
if _env_allowed:
    ALLOWED_HOSTS = _env_allowed
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    ALLOWED_HOSTS = []

# Azure App Service (and similar proxies): correct scheme/host for Channels / TLS.
if os.environ.get('WEBSITE_INSTANCE_ID'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'instruction_presenter',
]

MIDDLEWARE = [
    'config.azure_host_middleware.AzureInternalHostMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Shared across HTTP workers in-process only; use Redis cache for multi-worker.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'instruction-presenter-manifest',
    }
}

# Seconds to keep instruction manifest (base_url, file list, redirect URLs).
INSTRUCTION_MANIFEST_TTL = 86400

# Hosts allowed in complete_url / staff_complete_url (comma-separated env).
# If unset, manifest.redirect_allowed_hosts() falls back to ALLOWED_HOSTS.
_redirect_env = _hosts_from_env('INSTRUCTION_REDIRECT_ALLOWED_HOSTS')
INSTRUCTION_REDIRECT_ALLOWED_HOSTS = _redirect_env if _redirect_env else None

# If True, only https: redirects are accepted (ignored for relative URLs).
INSTRUCTION_REDIRECT_REQUIRE_HTTPS = os.environ.get(
    'INSTRUCTION_REDIRECT_REQUIRE_HTTPS', ''
).strip().lower() in ('1', 'true', 'yes')


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Optional overrides (not in repo): must run last so ALLOWED_HOSTS / DEBUG / etc. win.
try:
    from .local_settings import *  # noqa: F403, E402
except ImportError:
    pass
