"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv() -> None:
    """Load KEY=VALUE lines from a project .env without overriding existing env."""
    path = BASE_DIR / '.env'
    if not path.is_file():
        return
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        if not key:
            continue
        os.environ.setdefault(key, value.strip().strip('"').strip("'"))


_load_dotenv()


def _hosts_from_env(var_name: str) -> list[str]:
    """Comma-separated hostnames; whitespace trimmed; empty entries dropped."""
    raw = os.environ.get(var_name, '')
    if not raw:
        return []
    return [h.strip() for h in raw.split(',') if h.strip()]


def _allowed_hosts_from_environment() -> list[str]:
    """
    ALLOWED_HOSTS env: comma-separated list (e.g. app.azurewebsites.net,custom.domain).
    On Azure App Service, WEBSITE_HOSTNAME is appended if not already listed.
    """
    hosts: list[str] = []
    seen: set[str] = set()
    for h in _hosts_from_env('ALLOWED_HOSTS'):
        key = h.lower()
        if key not in seen:
            seen.add(key)
            hosts.append(h)
    website = os.environ.get('WEBSITE_HOSTNAME', '').strip()
    if website and website.lower() not in seen:
        hosts.append(website)
    return hosts


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7*4^8zs@bf%!lwjgeb=_2^(lp9t&^td$*0um9^b4p&16^n7z8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

_env_allowed = _allowed_hosts_from_environment()
if _env_allowed:
    ALLOWED_HOSTS = _env_allowed
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    ALLOWED_HOSTS = []

# Azure App Service (and similar proxies): correct scheme/host for Channels / TLS.
if os.environ.get('WEBSITE_INSTANCE_ID'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'instruction_presenter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Instruction sessions live in the database. This cache is unused by that data.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'instruction-presenter',
    }
}

# Hosts allowed in complete_url / staff_complete_url (comma-separated env).
# If unset, manifest.redirect_allowed_hosts() falls back to ALLOWED_HOSTS.
_redirect_env = _hosts_from_env('INSTRUCTION_REDIRECT_ALLOWED_HOSTS')
INSTRUCTION_REDIRECT_ALLOWED_HOSTS = _redirect_env if _redirect_env else None

# If True, only https: redirects are accepted (ignored for relative URLs).
INSTRUCTION_REDIRECT_REQUIRE_HTTPS = os.environ.get(
    'INSTRUCTION_REDIRECT_REQUIRE_HTTPS', ''
).strip().lower() in ('1', 'true', 'yes')


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def _postgres_database_from_url(url: str) -> dict:
    parsed = urlparse(url)
    if parsed.scheme.lower() not in ('postgres', 'postgresql'):
        raise ValueError(f'Unsupported DATABASE_URL scheme: {parsed.scheme}')
    query = parse_qs(parsed.query)
    options = {}
    if query.get('sslmode'):
        options['sslmode'] = query['sslmode'][-1]
    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }
    if options:
        config['OPTIONS'] = options
    return config


def _databases_from_environment() -> dict:
    """Postgres when DATABASE_URL or POSTGRES_HOST is set; otherwise SQLite."""
    url = os.environ.get('DATABASE_URL', '').strip()
    if url:
        return {'default': _postgres_database_from_url(url)}
    host = os.environ.get('POSTGRES_HOST', '').strip()
    if host:
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('POSTGRES_DB', 'instruction_presenter'),
                'USER': os.environ.get('POSTGRES_USER', 'instruction_presenter'),
                'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
                'HOST': host,
                'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            }
        }
    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


DATABASES = _databases_from_environment()


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'instruction_presenter:staff_index'
LOGOUT_REDIRECT_URL = 'login'

# Optional overrides (not in repo): must run last so ALLOWED_HOSTS / DEBUG / etc. win.
try:
    from .local_settings import *  # noqa: F403, E402
except ImportError:
    pass
