# Generated by Django 5.2.13 on 2026-10-08 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.TextField()),
                ('files', models.JSONField()),
                ('complete_url', models.TextField(blank=True, default='')),
                ('staff_complete_url', models.TextField(blank=True, null=True)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('media_playing', models.BooleanField(default=False)),
                ('media_position', models.FloatField(default=0)),
                ('media_anchor', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_key', models.UUIDField()),
                ('complete_url', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='instruction_presenter.instructionsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'player_key'), name='unique_subject_completion')],
            },
        ),
    ]
